resources:
  - ../../base

namespace: default

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: default
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: "default"

