resources:
  - ../../base
  - postgres-svc.yaml

namespace: default

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: accounts-secret
    files:
      - props.txt
# for some reason the content props.txt cannot be inline using literal, the new line will always get removed