quarkus:
  datasource:
    devservices:
      image-name: docker.io/postgres:12.7
    metrics:
      enabled: true
    db-kind: postgresql
    jdbc:
      enable-metrics: true
    reactive:
      max-size: 20
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
  log:
    console:
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
  jacoco:
    excludes: "**/model/*.class"
  jib:
    base-jvm-image: adoptopenjdk/11-jre
  shutdown:
    timeout: 30
  http:
    port: 8080
    test-port: 0
  vertx:
    worker-pool-size: 50
