quarkus:
  datasource:
    db-kind: postgresql
    metrics:
      enabled: true
    devservices:
      image-name: postgres:12.7
  log:
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
  flyway:
    migrate-at-start: true
    baseline-on-migrate: false # setup to true to use a new schema
  jacoco:
    excludes: "**/model/*.class"
  http:
    test-port: 0
#     uncomment jaeger server-name will trigger sending trace info to jaeger endpoint
#     jaeger:
#       server-name: account-reactive

"%demo":
  quarkus:
    datasource:
      db-kind: postgresql
      username: pocuser
      password: password
      jdbc:
        url: jdbc:postgresql://192.168.20.71:5432/poc
      reactive:
        url: postgresql://192.168.20.71:5432/poc
    log:
      file:
        enable: false
        path: junk.log
  # Send output to a trace.log file under the /tmp directory
