quarkus:
  log:
    console:
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
  jacoco:
    excludes: "**/model/*.class"
  shutdown:
    timeout: 30
  http:
    port: 8080
    test-port: 0
  vertx:
    worker-pool-size: 50
  mongodb:
    credentials:
      username: dev
      password: dev
      auth-mechanism: SCRAM-SHA-1
      auth-source: dev

    connection-string: mongodb://localhost:27017
    # max-pool-size: 300
    metrics:
      enabled: true

app:
  database: dev