---
openapi: 3.0.0
info:
  title: Vino Bank API
  description: This is a banking api
  contact:
    email: lee@vino9.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: /
tags:
- name: get_account_detail
  description: Get Account Details
paths:
  /accounts/{id}:
    get:
      summary: get account for account number
      description: Get Account Details for one account
      operationId: getAccountDetail
      parameters:
      - name: id
        in: path
        description: account id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountDetail'
        "400":
          description: bad input parameter
        "401":
          description: access denied
components:
  schemas:
    Balance:
      required:
      - available
      - balanceDate
      - ledger
      type: object
      properties:
        available:
          type: number
          example: 100.01
        ledger:
          type: number
          example: 100.02
        balanceDate:
          type: string
          format: date
          example: 2016-08-29
    AccountDetail:
      required:
      - accountNo
      - currency
      - balance
      - branchCode
      - country
      type: object
      properties:
        accountNo:
          type: string
          example: "10001001"
        currency:
          maxLength: 3
          minLength: 3
          type: string
          example: "SGD"
        country:
          type: string
          maxLength: 2
          minLength: 2
          example: "SG"
        branchCode:
          type: string
          example: "2002"
        balance:
          type: array
          items:
            $ref: '#/components/schemas/Balance'
