apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: gcr.io/vino9-276317/accounts
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
          volumeMounts:
            - name: secret
              mountPath: "./work/config"
              readOnly: true
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.25"
      volumes:
        - name: secret
          secret:
            secretName: accounts-secret
            items:
              - key: props.txt
                path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  type: NodePort
  selector:
    app: accounts
  ports:
    - name: http
      port: 8080
