apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: accounts
  labels:
    target: prometheus
spec:
  selector:
    matchLabels:
      app: accounts
  endpoints:
    - port: http
      path: /q/metrics
