name: Build a container image and publish to GitHub package

on:
  push:
    branches: [master]
#on:
#  push:
#    tags:
#      - v1.*
#      - v2.*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MVN: mvn --show-version --batch-mode

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: jdk11
          uses: actions/setup-java@v2
          with:
            java-version: "11"
            distribution: "adopt"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Cache ~/.m2
          uses: actions/cache@v2
          with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2

      - name: Build and Unit Test
        run:
          $MVN clean test

      - name: Build and push image using JIB
        run: >
          $MVN package -DskipTests
          -Dquarkus.container-image.push=true
          -Dquarkus.container-image.registry=${{ env.REGISTRY }}
          -Dquarkus.container-image.name=${{ env.IMAGE_NAME }}
          -Dquarkus.container-image.tag=test
          -Dquarkus.jib.platforms=linux/amd64,linux/aarch64
