name: Build a container image and publish to GitHub package

on:
  push:
    branches: [master]
    tags:
      - v1.*
      - v2.*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MVN: mvn --show-version --batch-mode

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: jdk11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache ~/.m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Unit Test
        run: $MVN clean test

      - name: Extract tag or branch name
        id: get_tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Build and push image using JIB
        run: >
          $MVN package -DskipTests
          -Dquarkus.container-image.registry=${{ env.REGISTRY }}
          -Dquarkus.container-image.group=${{ github.actor }}
          -Dquarkus.container-image.push=${{ github.event_name != 'pull_request' }}
          -Dquarkus.container-image.tag=${{ steps.get_tag.outputs.TAG }}
          -Dquarkus.container-image.additional-tags=${{ github.sha }}
          -Dquarkus.jib.platforms=linux/amd64,linux/aarch64
